name: "Hyperion.NG (host network)"
slug: "hyperion_ng"
description: "Runs Hyperion.NG using sirfragalot/hyperion.ng with host networking."
version: "1.0.0"
url: "https://hub.docker.com/r/sirfragalot/hyperion.ng"

arch:
  - amd64
  - aarch64
  - armv7

image: "sirfragalot/hyperion.ng"

host_network: true

map:
  - type: addon_config
    read_only: false
    path: /root/.hyperion

startup: application
boot: auto

webui: "http://[HOST]:[PORT:8090]/"